[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "postgresql"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npx prisma generate"
]

[phases.start]
cmd = "node src/index.js"